language: c
compiler:
  - gcc
  - clang

script:
   - echo Temporarily disabled until cmake issues are sorted out
#  - cd build && cmake .. && make && ./test/test --color --extended 2>test_log_default && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..
#  - cd build && cmake .. -DNO_ASM=on && make && ./test/test --color --extended 2>test_log_no_asm && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..
#  - cd build && cmake .. -DNATIVE_ARCH=on && make && ./test/test --color --extended 2>test_log_native_arch && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..

after_failure:
  - cd build && cat ./tests_log_debug && cd ..
  - cd build && cat ./tests_log_sharedlib && cd ..
  - cd build && cat ./tests_log_default && cd ..
