language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update

install:
  - cd /tmp/
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.1.tar.gz
  - tar -xvf cmake-2.8.12.1.tar.gz
  - cd cmake-2.8.12.1
  - ./configure
  - make
  - sudo make install
  - sudo apt-get install nasm

script:
  - cd build && cmake .. && make -j 4 && ./test/test --color --extended 2>test_log_generic && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..
  - cd build && cmake .. -DARCH=amd64 && make -j 4 && ./test/test --color --extended 2>test_log_arch && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..

after_failure:
  - cd build && cat ./tests_log_generic && cd ..
  - cd build && cat ./tests_log_arch && cd ..
