language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update

install:
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.1.tar.gz
  - tar -xvf cmake-2.8.12.1.tar.gz
  - cd cmake-2.8.12.1
  - ./configure
  - make -j 4
  - sudo make install
  - cd ..
  - sudo apt-get install nasm

script:
  - cd build && cmake .. -DLTO=off && make -j 4 && ./test/test --color && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..
  - cd build && cmake .. -DLTO=off -DARCH=amd64 && make -j 4 && ./test/test --color && rm -rf `find .|grep -v '\.gitignore'|grep -v '\.$'` && cd ..

