language: c
compiler:
  - gcc
  - clang

script:
  - make clean && make debug=1 && make tests && ./tests/bin/tests -color -extended 2>tests_log_debug
  - make clean && make shared=1 && make tests shared=1 && ./tests/bin/tests -color -extended 2>tests_log_sharedlib
  - make clean && make && make tests && ./tests/bin/tests -color -extended 2>tests_log_default

after_failure:
  - cat ./tests_log_debug
  - cat ./tests_log_sharedlib
  - cat ./tests_log_default
