language: c
compiler:
  - gcc
#  - clang  (not ready yet)

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install nasm

script:
  - ./build.py configure && ./build.py build && ./build.py test && ./build.py clean
  - ./build.py configure --arch amd64 && ./build.py build && ./build.py test && ./build.py clean
