#!/usr/bin/env python

''' The purpose of this script is to extract struct definitions
    for primitives from source files that are being built (this
    is provided via command-line arguments) and write them into
    a header file so they can be made public to the user.
    
    This will be moved into the CMake script eventually but due
    to the nontrivial nature of the operation it is much easier
    to prototype in Python for the moment.                      '''

from sys import argv

class Primitive:
    def __init__(self, name):
        self.name = name

primitives = [Primitive("rc4.c"),
              Primitive("md5.c"),
              Primitive("sha256.c"),
              Primitive("skein256.c")]

def extract_struct(path, prim):
    with open(path, "r") as f:
        content = f.readlines()
    
    for i, line in enumerate(content):
        if line == "#if annotation\n":
            p1 = i
            break
    
    for i, line in enumerate(content):
        if (line == "#endif /* annotation */\n") and (i > p1):
            p2 = i
            break

    buf = ""
    
    for i in range(p1 + 1, p2):
        buf += content[i]
    
    return buf

if __name__ == "__main__":
    in_use = []
    
    for arg in argv:
        for prim in primitives:
            if prim.name in arg:
                in_use.append((arg, prim))
    
    platform =  "#ifndef ORDO_PLATFORM_H\n"
    platform += "#define ORDO_PLATFORM_H\n"
    platform += "\n/* AUTOGENERATED - DO NOT EDIT */\n\n"
    
    for (path, prim) in in_use:
        platform += extract_struct(path, prim) + "\n"
    
    platform += "#endif"
    
    with open('include/ordo/platform.h', 'w') as f:
        f.write(platform)
    
    # done!
