/* AUTOGENERATED - DO NOT EDIT */

#ifndef ORDO_DEFINITIONS_H
#define ORDO_DEFINITIONS_H

#include "ordo/common/identification.h"

#define HASH_BLOCK_LEN  64
#define HASH_DIGEST_LEN 32
#define BLOCK_BLOCK_LEN 32

struct AES_STATE
{
    unsigned char key[336];
    size_t rounds;
};

struct NULLCIPHER_STATE
{
    uint8_t dummy;
};

struct THREEFISH256_STATE
{
    uint64_t subkey[19 * 4];
};

struct MD5_STATE
{
    /* Here block_len is used to track incomplete input blocks, whereas
     * msg_len stores the total message length so far (for padding). */
    uint32_t digest[4];
    uint32_t block[16];
    uint64_t block_len;
    uint64_t msg_len;
};

struct SHA256_STATE
{
    uint32_t digest[8];
    uint32_t block[16];
    uint64_t block_len;
    uint64_t msg_len;
};

struct SKEIN256_STATE
{
    uint64_t state[4];
    uint64_t block[4];
    uint64_t block_len;
    uint64_t msg_len;
    uint64_t out_len;
    struct THREEFISH256_STATE cipher;
};

struct RC4_STATE
{
    uint8_t i;
    uint8_t j;
    uint8_t s[256];
};

struct ECB_STATE
{
    unsigned char block[BLOCK_BLOCK_LEN];
    size_t available;

    size_t block_size;

    size_t padding;
    int direction;
};

struct CBC_STATE
{
    unsigned char iv[BLOCK_BLOCK_LEN];
    unsigned char block[BLOCK_BLOCK_LEN];
    size_t available;

    size_t block_size;

    size_t padding;
    int direction;
};

struct CTR_STATE
{
    unsigned char iv[BLOCK_BLOCK_LEN];
    unsigned char counter[BLOCK_BLOCK_LEN];
    size_t remaining;
    size_t block_size;
};

struct CFB_STATE
{
    unsigned char iv[BLOCK_BLOCK_LEN];
    unsigned char tmp[BLOCK_BLOCK_LEN];
    size_t remaining;
    size_t block_size;
    int direction;
};

struct OFB_STATE
{
    unsigned char iv[BLOCK_BLOCK_LEN];
    size_t remaining;
    size_t block_size;
};

struct BLOCK_STATE
{
    prim_t primitive;

    union
    {
        struct AES_STATE aes;
        struct NULLCIPHER_STATE nullcipher;
        struct THREEFISH256_STATE threefish256;
    } jmp;
};

struct HASH_STATE
{
    prim_t primitive;

    union
    {
        struct MD5_STATE md5;
        struct SHA256_STATE sha256;
        struct SKEIN256_STATE skein256;
    } jmp;
};

struct STREAM_STATE
{
    prim_t primitive;

    union
    {
        struct RC4_STATE rc4;
    } jmp;
};

struct BLOCK_MODE_STATE
{
    prim_t primitive;

    union
    {
        struct ECB_STATE ecb;
        struct CBC_STATE cbc;
        struct CTR_STATE ctr;
        struct CFB_STATE cfb;
        struct OFB_STATE ofb;
    } jmp;
};

#endif
