#ifndef ORDO_PLATFORM_H
#define ORDO_PLATFORM_H

/* AUTOGENERATED - DO NOT EDIT */

#define USING_MD5
struct MD5_STATE
{
    /* Here block_len is used to track incomplete input blocks, whereas
     * msg_len stores the total message length so far (for padding). */
    uint32_t digest[4];
    uint32_t block[16];
    uint64_t block_len;
    uint64_t msg_len;
};

#define USING_RC4
struct RC4_STATE
{
    uint8_t i;
    uint8_t j;
    uint8_t s[256];
};

#define USING_SHA256
struct SHA256_STATE
{
    uint32_t digest[8];
    uint32_t block[16];
    uint64_t block_len;
    uint64_t msg_len;
};

#define USING_SKEIN256
struct SKEIN256_STATE
{
    uint64_t state[4];
    uint64_t block[4];
    uint64_t block_len;
    uint64_t msg_len;
    uint64_t out_len;
    unsigned char cipher[2048];
};

struct HASH_STATE
{
    enum HASH_FUNCTION hash;

    union
    {
        struct MD5_STATE md5;
        struct SHA256_STATE sha256;
        struct SKEIN256_STATE skein256;
    } jmp;
};

struct STREAM_STATE
{
    enum STREAM_CIPHER cipher;

    union
    {
        struct RC4_STATE rc4;
    } jmp;
};

#endif