/*===-- common/interface.h -----------------------------*- PUBLIC -*- H -*-===*/
/**
*** @file
*** @brief API
***
*** This header contains  some preprocessor  definitions which try to abstract
*** compiler-specific features  (such as packing, export  mechanisms, aliasing
*** semantics), and will be included in every other header in the library.
***
*** The definitions.h header is autogenerated by the build system, and depends
*** on the architecture and the primitives built into the library.
**/
/*===----------------------------------------------------------------------===*/

#ifndef ORDO_INTERFACE_H
#define ORDO_INTERFACE_H

/** @cond **/
#include <stddef.h>
#include <stdint.h>
/** @endcond **/

/*===----------------------------------------------------------------------===*/

#if defined(BUILDING_ORDO) || defined(BUILDING_ordo)
    #if defined(ORDO_EXPORTS) || defined(ordo_EXPORTS)
        #define BUILD_SHARED
    #endif
#else
    #if !defined(ORDO_STATIC_LIB)
        #define USING_SHARED
    #endif
#endif

#if defined(__MINGW32__) || defined(_MSC_VER)
    #if defined(BUILD_SHARED)
        #define ORDO_PUBLIC __declspec(dllexport)
        #define ORDO_HIDDEN
    #elif defined(USING_SHARED)
        #define ORDO_PUBLIC __declspec(dllimport)
        #define ORDO_HIDDEN
    #else
        #define ORDO_PUBLIC
        #define ORDO_HIDDEN
    #endif
#elif defined(__clang__) || defined(__INTEL_COMPILER) || defined(__GNUC__)
    #if defined(BUILD_SHARED)
        #define ORDO_PUBLIC __attribute__((visibility("default")))
        #define ORDO_HIDDEN __attribute__((visibility("hidden")))
    #elif defined(USING_SHARED)
        #define ORDO_PUBLIC __attribute__((visibility("default")))
        #define ORDO_HIDDEN __attribute__((visibility("hidden")))
    #else
        #define ORDO_PUBLIC
        #define ORDO_HIDDEN
    #endif
#else
    #error "Unsupported compiler!"
#endif

#if defined(__clang__)
    #define RESTRICT __restrict__
#elif defined(__INTEL_COMPILER)
    #define RESTRICT restrict
#elif defined(__GNUC__)
    #define RESTRICT __restrict__
#elif defined(_MSC_VER)
    #define RESTRICT __restrict
#endif

#undef BUILD_SHARED
#undef USING_SHARED

/*===----------------------------------------------------------------------===*/

#include "ordo/definitions.h"

/*===----------------------------------------------------------------------===*/

#endif
